version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10  
    commands:
    - yarn install
    build:
    - yarn build
    post_build:
    - aws s3 sync build s3://sn-react-test --delete